# https://rust-lang.github.io/rustfmt

unstable_features = true

group_imports = "StdExternalCrate"
imports_granularity = "Item"
normalize_comments = true
normalize_doc_attributes = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
